name: Update Data (GI)

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 12 * * *'

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Swift
              uses: swift-actions/setup-swift@v2

            - name: Update Data
              id: compare_shas
              run: |
                swift ./UpdateData4GI.swift

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: update-data-${{ github.run_number }}
                base: main
                title: "Update Data (GI)"
                body: |
                  This PR updates all external data which are CI-updatable.
                delete-branch: true
                assignees: ShikiSuen
                reviewers: ShikiSuen
                team-reviewers: |
                  owners
                  maintainers
